apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rnrphznb8-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/rnrphznb8-nodejs-gitops